services:

  auth-service:
    build: ./auth
    container_name: auth-service
    environment:
      - SERVER_PORT=5001
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "5001:5001"
    networks:
      - micro-net

  product-service:
    build: ./product
    container_name: product-service
    environment:
      - SERVER_PORT=5002
      - SERVER_ADDRESS=0.0.0.0
    ports:
      - "5002:5002"
    networks:
      - micro-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
      - AUTH_SERVICE_URL=http://auth-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - product-service
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
